site_name: FlashFS Documentation
site_description: Documentation for FlashFS - A high-performance file system snapshot and diff tool
site_author: Thomas F McGeehan V
repo_url: https://github.com/TFMV/flashfs
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: mermaid

plugins:
  - search
  - git-revision-date-localized:
      type: date

nav:
  - Home: index.md
  - Components:
      - CLI: cli.md
      - Walker: walker.md
      - Serializer: serializer.md
      - Schema: schema.md
      - Storage: storage.md
  - Features:
      - Diff Computation: diff-computation.md
      - Expiry Policy: expiry-policy.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TFMV/flashfs
  version:
    provider: mike
