// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flashfs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Diff struct {
	_tab flatbuffers.Table
}

func GetRootAsDiff(buf []byte, offset flatbuffers.UOffsetT) *Diff {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Diff{}
	x.Init(buf, n+offset)
	return x
}

func FinishDiffBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDiff(buf []byte, offset flatbuffers.UOffsetT) *Diff {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Diff{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDiffBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Diff) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Diff) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Diff) Entries(obj *DiffEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Diff) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DiffStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DiffAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func DiffStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DiffEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
